### ISSUE TITLE
Add linter support for "&" in CSS nesting

### ISSUE THREAD

**Issue by onetrev** [KevinBatdorf/pattern-css#117]
A very minor and nit-picky item, but I was an early adopter of CSS nesting, and in those days you _had_ do use the ampersand for nesting. It's now become a habit even though it is optional in the CSS spec that landed. Personally, I also still like it because it's clear what you are doing and it's more-readable (in my opinion).

Long story short, any chance you can tweak the linter so it doesn't show as an error (highlighted in red). I noticed the CSS still works with the ampersand though so that's the good part and I can live with that if not. :)

![Screenshot 2024-09-16 191140](https://github.com/user-attachments/assets/35fa9767-2584-442f-a1f2-6c5881115fb6)

**Comment by KevinBatdorf** [comment]
The parser returns line number with errors so maybe they are misreporting it. I'll look into it though. Maybe there's something I can do to filter out those errors.

**Comment by KevinBatdorf** [comment]
This should be fixed now in 1.2.6. Thanks again for reporting this.

**Comment by onetrev** [comment]
Yes, confirmed fixed! And more so, thank you for fixing this and so quickly. 🎉
