### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by KevinBatdorf** [KevinBatdorf/pattern-css#2]
If you want to test out a build, go to the Actions tab and download the build artifact. The `main` branch should be stable, while other branches related to features, etc.

https://github.com/KevinBatdorf/pattern-css/actions/workflows/build-production-zip.yml

![Screen Shot 2023-01-29 at 10 17 56 PM](https://user-images.githubusercontent.com/1478421/215380281-c1fe1735-9f8b-4fa3-aeb2-10986f04be19.png)

If there's no build available, comment here and I'll run a new one

**Comment by KevinBatdorf** [comment]
Hey, just ran it now:

https://github.com/KevinBatdorf/per-page-css/actions/runs/4222089085

> I assume this is a early test version though. Any ETA you want to publish it?

I don't think WP will accept it. They have a policy not to accept any _new_ plugins that execute css or js, no matter how safely it's handled. 

I still want to add more features, but it's a bit of a bummer it won't live in the repository so there's less incentive I guess.

**Comment by ouun** [comment]
Thanks a lot!

> I still want to add more features, but it's a bit of a bummer it won't live in the repository so there's less incentive I guess.

Totally understand that. IMO: On the other side many WP plugins only live in their repositories e.g. on GitHub. Publishing releases here with the option to install them via Composer is a great alternative. People not using Composer can use [Git Updater](https://git-updater.com/) plugins to stay on track.

**Comment by KevinBatdorf** [comment]
Yeah It's not a bad idea. I could also include something built-in easily enough too. It would require including the build files in the repo, which isn't a huge deal I guess.

I'll think about it. I want to focus on the [code block](https://github.com/KevinBatdorf/code-block-pro) plugin for a bit but maybe after a few updates there I'll get excited with this one again. Let me know if you have any feedback.

**Comment by KevinBatdorf** [comment]
I've set the build to run once a day and create an artifact, so no need to ask for me to build it. 

https://github.com/KevinBatdorf/per-page-css/actions/workflows/build-production-zip.yml

There are also integration tests running daily on the current WP release, as well as the next dev branch. That way if the plugin breaks I will be notified. 

https://github.com/KevinBatdorf/per-page-css/actions/workflows/cypress-main.yml

**Comment by KevinBatdorf** [comment]
Going to open a new issue with updated instructions since the plugin has changed a bit
